alias ls="eza -G --color --icons -a"
alias wallpaper="pkill hyprpaper || hyprpaper &"
alias cd="z"
alias p="paru -S"

alias gasm="git add . && git commit"
alias gc="git clone --depth=1"
alias gcd="git clone"
alias gac="git add . && git commit"
alias gacm="git add . && git commit --allow-empty-message"
alias gacmp='f(){ git add . && git commit --allow-empty-message -m "$1" && git push; }; f'
alias gacp="git add . && git commit && git push"
# alias gacmp="git add . && git commit --allow-empty-message \"\" && git push"
alias gpcu="git add . && git commit -m \"config updated $(date)\" && git push"
alias love="/home/benc/.local/share/AppImage/love-11.5-x86_64.AppImage"
alias nvim-word="NVIM_APPNAME=nvim-word nvim"
